[tool.poetry]
name = "app-python"
version = "0.1.0"
description = ""
authors = ["Fedor Ivanov <ivnfedor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.109.0"
pytz = "^2023.4"
uvicorn = {extras = ["standard"], version = "^0.27.0.post1"}
httpx = "^0.26.0"
prometheus-fastapi-instrumentator = "^7.0.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
