---
- name: Deploy web application
  ansible.builtin.include_tasks:
    file: "0-deploy.yml"
    apply:
      tags: deploy
  tags: deploy

- name: Wipe out web application
  when: web_app_full_wipe is defined and web_app_full_wipe
  ansible.builtin.include_tasks:
    file: "1-wipe.yml"
    apply:
      tags: wipe
  tags: wipe
