---

- name: Install Docker
  ansible.builtin.include_tasks: install_docker.yml

- name: Install docker-compose
  ansible.builtin.include_tasks: install_compose.yml

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
