name: Rust CI

on:
  push:
    branches: ["main"]
    paths:
      - "app_rust/**"
      - ".github/workflows/rust.yaml"
  pull_request:
    branches: ["main"]
    paths:
      - "app_rust/**"
      - ".github/workflows/rust.yaml"

env:
  IMAGE_NAME: simple-web-app
  IMAGE_TAG: rust-${{ github.sha }}

defaults:
  run:
    working-directory: app_rust

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup component add rustfmt
      - run: cargo fmt --all --check

  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup component add clippy
      - uses: Swatinem/rust-cache@158274163087d4d4d49dfcc6a39806493e413240
        with:
          workspaces: app_rust
      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  cargo-test:
    name: cargo test
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: rustup show
      - uses: Swatinem/rust-cache@158274163087d4d4d49dfcc6a39806493e413240
        with:
          workspaces: app_rust
      - name: Run tests
        run: cargo test --all-features

  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@3d58c274f17dffee475a5520cbe67f0a882c4dbb
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx to enable caching
        uses: docker/setup-buildx-action@edfb0fe6204400c56fbfd3feba3fe9ad1adfa345

      - name: Build and push Docker image
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        with:
          context: app_rust
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
